[[SettingItems]]
Group = "Graphic"
Key = "WaitVSync"
Description = "VSync (requires restart)"
Type = "Boolean"
Values = [ "On", "Off" ]
Default = false

[[SettingItems]]
Group = "Graphic"
Key = "Fullscreen"
Description = "Fullscreen (requires restart)"
Type = "Boolean"
Values = [ "On", "Off" ]
Default = false

[[SettingItems]]
Group = "Graphic"
Key = "DivisionLine"
Description = "Number of lane divisions"
Type = "IntegerSelect"
Values = [ 1, 2, 4, 8, 16 ]
Default = 8

[[SettingItems]]
Group = "Graphic"
Key = "ShowSlideLine"
Description = "Show slide center line"
Type = "Boolean"
Values = [ "On", "Off" ]
Default = true

[[SettingItems]]
Group = "Graphic"
Key = "SlideLineThickness"
Description = "Slide center line thickness"
Type = "Float"
Range = [ 0.0, 32.0 ]
Step = 0.5
Default = 16.0

[[SettingItems]]
Group = "Graphic"
Key = "ShowAirActionJudgeLine"
Description = "Show Air Judge Line"
Type = "Boolean"
Values = [ "On", "Off" ]
Default = true

[[SettingItems]]
Group = "Play"
Key = "EnableAutoPlay"
Description = "Autoplay"
Type = "Boolean"
Values = [ "On", "Off" ]
Default = true

[[SettingItems]]
Group = "Play"
Key = "Hispeed"
Description = "Hi-Speed"
Type = "Float"
Range = [ 1.0, 30.0 ]
Step = 0.2
Default = 6.0

[[SettingItems]]
Group = "Play"
Key = "AirRollMultiplier"
Description = "AirRollMultiplier (TRANSLATE ME)"
Type = "Float"
Range = [ 0.5, 4.0 ]
Step = 0.1
Default = 1.5

[[SettingItems]]
Group = "Play"
Key = "JudgeAdjustSlider"
Description = "Ground timing window offset (ms)"
Type = "Integer"
Range = [ -100, 100 ]
Step = 1
Default = 0

[[SettingItems]]
Group = "Play"
Key = "JudgeMultiplierSlider"
Description = "Ground timing window multiplier"
Type = "Float"
Range = [ 1.0, 10.0 ]
Step = 0.1
Default = 1.0

[[SettingItems]]
Group = "Play"
Key = "JudgeAdjustAirString"
Description = "Air timing window offset (ms)"
Type = "Integer"
Range = [ -1000, 1000 ]
Step = 1
Default = 50

[[SettingItems]]
Group = "Play"
Key = "JudgeMultiplierAirString"
Description = "Air timing window multiplier"
Type = "Float"
Range = [ 1.0, 20.0 ]
Step = 0.1
Default = 4.0

[[SettingItems]]
Group = "Sound"
Key = "BufferLatency"
Description = "Offset compensation (ms)"
Type = "Integer"
Range = [ -500, 500 ]
Step = 1
Default = 30

[[SettingItems]]
Group = "Sound"
Key = "VolumeTap"
Description = "Tap Volume"
Type = "Float"
Range = [ 0.0, 1.0 ]
Step = 0.01
Default = 1.0

[[SettingItems]]
Group = "Sound"
Key = "VolumeExTap"
Description = "ExTap Volume"
Type = "Float"
Range = [ 0.0, 1.0 ]
Step = 0.01
Default = 1.0

[[SettingItems]]
Group = "Sound"
Key = "VolumeFlick"
Description = "Flick Volume"
Type = "Float"
Range = [ 0.0, 1.0 ]
Step = 0.01
Default = 1.0

[[SettingItems]]
Group = "Sound"
Key = "VolumeAir"
Description = "Air Volume"
Type = "Float"
Range = [ 0.0, 1.0 ]
Step = 0.01
Default = 1.0

[[SettingItems]]
Group = "Sound"
Key = "VolumeAirAction"
Description = "AirAction Volume"
Type = "Float"
Range = [ 0.0, 1.0 ]
Step = 0.01
Default = 1.0

[[SettingItems]]
Group = "Sound"
Key = "VolumeHold"
Description = "Hold Volume"
Type = "Float"
Range = [ 0.0, 1.0 ]
Step = 0.01
Default = 1.0

[[SettingItems]]
Group = "Sound"
Key = "VolumeSlide"
Description = "Slide Volume"
Type = "Float"
Range = [ 0.0, 1.0 ]
Step = 0.01
Default = 1.0
